//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace assignment_draft
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Cart
    {
        public int CartId { get; set; }
        public string ClientId { get; set; }
        public Nullable<bool> IsInBasket { get; set; }
        public int ProductId { get; set; }
        public decimal Price { get; set; }
        public int Quantity { get; set; }
        public int ImageId { get; set; }
        public string Extension { get; set; }
    
        public virtual tbl_products tbl_products { get; set; }
        public virtual tb_images tb_images { get; set; }
    }
}
