//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace assignment_draft
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_products
    {
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public string ProductDesc { get; set; }
        public Nullable<int> StockQty { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> ImageId { get; set; }
        public string CategoryId { get; set; }
        public string Condition { get; set; }
    
        public virtual tb_categories tb_categories { get; set; }
        public virtual tb_images tb_images { get; set; }
    }
}
