//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace assignment_draft
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_products()
        {
            this.tb_Cart = new HashSet<tb_Cart>();
        }
    
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public string ProductDesc { get; set; }
        public Nullable<int> StockQty { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> ImageId { get; set; }
        public string CategoryId { get; set; }
        public string Condition { get; set; }
        public Nullable<bool> IsOnSale { get; set; }
        public Nullable<bool> StockCondition { get; set; }
    
        public virtual tb_categories tb_categories { get; set; }
        public virtual tb_images tb_images { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Cart> tb_Cart { get; set; }
    }
}
