//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace assignment_draft.App_Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_1525603_qiwebEntities : DbContext
    {
        public db_1525603_qiwebEntities()
            : base("name=db_1525603_qiwebEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_categories> tb_categories { get; set; }
        public virtual DbSet<tb_images> tb_images { get; set; }
        public virtual DbSet<tb_products> tb_products { get; set; }
    }
}
