//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace assignment_draft.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_products
    {
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public string ProductDesc { get; set; }
        public int StockQty { get; set; }
        public decimal Price { get; set; }
        public string ImageId { get; set; }
        public string CategoryId { get; set; }
    }
}
